"""Read-only composition of a proposal review and non-executable review-test draft."""

from __future__ import annotations

from typing import Any

from authzest.codex.contracts import identity
from authzest.codex.preview import ValidatedPreviewBundle, preview_bundle, validate_preview_bundle
from authzest.codex.proposals import content_hash
from authzest.codex.review_demo import REVIEW_DEMO_CASE_ID, build_review_demo_bundle
from authzest.runner.proposal_check import check_proposal

REVIEW_SCHEMA_VERSION = "1.0"
TEST_DRAFT_SCHEMA_VERSION = "1.0"
TEST_DRAFT_TEMPLATE_VERSION = "1.0"
_TEMPLATES = {
    "dependency-declarations": (
        "Dependency-declaration regression review",
        (
            "Review the bound source snapshots and the selected registration.",
            "Compare explicit supported dependency declarations with the caller's expected count.",
        ),
        "A syntactic count does not prove callable behavior, authentication or access control.",
    ),
    "scope-declarations": (
        "Declared-scope regression review",
        (
            "Review the explicit Security scope declarations for the bound registration.",
            "Compare the declared scope set with the caller-authored expectation.",
        ),
        "Declared scopes do not prove token validation, scope checking or policy enforcement.",
    ),
    "policy-intent": (
        "Manual policy-intent review",
        (
            "Read the cited policy and the caller-authored intended access.",
            "Request separate human review of intended behavior and missing implementation.",
        ),
        "Policy intent is not inferred or evaluated by the source-declaration checker.",
    ),
}


def _test_draft(bundle: ValidatedPreviewBundle, payload: dict[str, Any]) -> dict[str, Any]:
    request = payload["request"]
    proposal = payload["proposal"]
    manifest = payload["manifest"]
    source_ids = {
        item["data"]["path"]: item["id"] for item in request["evidence"] if item["kind"] == "source"
    }
    cases = []
    for item in manifest["expectations"]:
        title, steps, limitation = _TEMPLATES[item["observation"]]
        cases.append(
            {
                **item,
                "title": title,
                "steps": list(steps),
                "limitations": [*item["limitations"], limitation],
                "status": "draft",
                "observed": None,
            }
        )
    draft = {
        "schema_version": TEST_DRAFT_SCHEMA_VERSION,
        "template_version": TEST_DRAFT_TEMPLATE_VERSION,
        "format": "structured-prose",
        "status": "draft",
        "executable": False,
        "provenance": "maintainer-authored-template",
        "verification_status": "not-run",
        "runtime_verification_status": "not-run",
        "authorization_verdict": "unknown",
        "bindings": {
            "bundle_id": bundle.bundle_id,
            "request_id": manifest["request_id"],
            "review_id": manifest["review_id"],
            "proposal_id": manifest["proposal_id"],
            "manifest_id": "expectation-" + identity(manifest),
            "source_identity": request["source_identity"],
        },
        "sources": [
            {
                "path": change["path"],
                "source_evidence_id": source_ids[change["path"]],
                "before_sha256": change["before_sha256"],
                "after_sha256": content_hash(change["after_text"]),
            }
            for change in proposal["changes"]
        ],
        "cases": cases,
        "limitations": [
            "Maintainer-authored prose templates, not AI-generated or executable tests.",
            "Expected values and policy interpretations come from the supplied manifest.",
            "No source code, shell command or HTTP request is generated by this test draft.",
            "Source comparison observations are separate; no runtime test outcome is claimed.",
            "Artifact IDs and exact content hashes bind this draft, not approval or authorship.",
            "No executor or approval flow consumes this draft, and it cannot resume a session.",
        ],
    }
    return {**draft, "draft_id": "regression-draft-" + identity(draft)}


def compose_review(bundle: ValidatedPreviewBundle) -> dict[str, Any]:
    """Compose detached views in memory; input artifact provenance is never invented.

    Zero provider calls describes this operation only, not historical usage in the
    supplied review. IDs are structural links, not authenticated author statements.
    """
    bundle = validate_preview_bundle(bundle.payload_json)
    payload = bundle.to_dict()
    return {
        "schema_version": REVIEW_SCHEMA_VERSION,
        "kind": "offline-integrated-review",
        "status": "completed",
        "bundle_id": bundle.bundle_id,
        "test_draft_provenance": "maintainer-authored-template",
        "source_artifact_provenance": "supplied-artifacts",
        "live_provider_calls": 0,
        "applied": False,
        "verification_status": "not-run",
        "runtime_verification_status": "not-run",
        "authorization_verdict": "unknown",
        "preview": preview_bundle(bundle),
        "comparison": check_proposal(bundle),
        "regression_test_draft": _test_draft(bundle, payload),
        "limitations": [
            "Read-only composition of supplied snapshots; no filesystem or Git freshness check.",
            "Comparison matches concern supported source declarations, never authorization.",
            "The regression-test draft contains prose only and has not been executed.",
            "Zero live provider calls refers only to composition, not supplied artifact history.",
            "Artifact identity and displayed provenance do not authenticate an author or approval.",
            "No provider call, target execution, file change or approval action is performed.",
        ],
    }


def run_review_demo() -> dict[str, Any]:
    """Review exactly one packaged mock example; no selected paths or automatic actions."""
    return {
        **compose_review(build_review_demo_bundle()),
        "demo": {
            "case_id": REVIEW_DEMO_CASE_ID,
            "artifact_provenance": "caller-authored-mock",
            "simulated_draft": True,
        },
    }
